# Hyperparameter Evolution Results
# Generations: 50
# Metrics:      0.892      0.26

lr: 0.00061
alpha1: 0.635
gamma1: 1.31
alpha2: 0.898
gamma2: 1.3
alpha3: 0.215
gamma3: 1.69
weight_decay: 0.0005
momentum: 0.931
